{{ config(materialized='incremental') }}
WITH DATETIME_CTE AS (
    SELECT DISTINCT
        {{ dbt_utils.generate_surrogate_key(['TPEP_DROPOFF_DATETIME']) }}  AS DATETIME_ID,
        T.TPEP_DROPOFF_DATETIME
    FROM {{ source('snowflake_tables', 'NYC_TAXI_TRIPS_SOURCE') }} T
    WHERE T.TPEP_DROPOFF_DATETIME IS NOT NULL

    {% if is_incremental() %}
    AND T.TPEP_DROPOFF_DATETIME > (
        SELECT MAX(this.DATETIME) FROM {{ this }} as this
    )
    {% endif %}
)
SELECT
    DATETIME_ID,
    TPEP_DROPOFF_DATETIME AS DATETIME,
    EXTRACT(YEAR FROM TPEP_DROPOFF_DATETIME) AS YEAR,
    EXTRACT(MONTH FROM TPEP_DROPOFF_DATETIME) AS MONTH,
    EXTRACT(DAY FROM TPEP_DROPOFF_DATETIME) AS DAY,
    EXTRACT(DAYOFWEEK FROM TPEP_DROPOFF_DATETIME) AS WEEKDAY,
    EXTRACT(HOUR FROM TPEP_DROPOFF_DATETIME) AS HOUR,
    EXTRACT(MINUTE FROM TPEP_DROPOFF_DATETIME) AS MINUTE,
    EXTRACT(SECOND FROM TPEP_DROPOFF_DATETIME) AS SECOND
FROM DATETIME_CTE