my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gxenyzd-mk35237

      # User/password auth
      user: dbt_test
      password: dbt_test

      role: ACCOUNTADMIN
      database: NYC_TAXI_TRIPS
      warehouse: COMPUTE_WH
      schema: public
      threads: 1
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)