name: Run NYC TAXI TRIPS Pipeline

on:
  push:
    tags:
      - "test"

jobs:
  run-astro-airflow:
    runs-on: self-hosted  # Utilise ton runner auto-hébergé
    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v4

      - name: Créer le fichier AWS config
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Créer le fichier AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Démarrer Astro
        run: astro dev start

      - name: se connecter au container airflow
        run: astro dev bash
       
      - name: Lancer le DAG nyc_taxi_trips
        run: airflow dags trigger nyc_taxi_trips