name: Run NYC TAXI TRIPS Pipeline

on:
  push:
    tags:
      - "test"

jobs:
  run-astro-airflow:
    runs-on: self-hosted  # Utilise ton runner auto-hébergé
    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v4

      - name: Créer les fichiers config AWS
        run: |
          set "dirName=./.aws"
          if not exist "%dirName%" (
              mkdir "%dirName%"
              echo Directory created: %dirName%
  
              echo "[default]" > %dirName%/config
              echo "region = $AWS_REGION" >> %dirName%/config

              echo "[default]" > %dirName%/credentials
              echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> %dirName%/credentials
              echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> %dirName%/credentials

          ) else (
              echo Directory already exists: %dirName%
          )

        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Démarrer Astro
        run: astro dev start

      - name: se connecter au container airflow
        run: astro dev bash
       
      - name: Lancer le DAG nyc_taxi_trips
        run: airflow dags trigger nyc_taxi_trips