name: Run NYC TAXI TRIPS Pipeline

on:
  push:
    tags:
      - "test"

jobs:
  run-astro-airflow:
    runs-on: self-hosted  # Utilise ton runner auto-hébergé
    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v4

      - name: Créer les fichiers config AWS
        run: |
          $folderPath = ".\.aws"

          if (-Not (Test-Path $folderPath)) {

            $configFilePath = "$folderPath\config"
            $configContent = @"
            [default]
            region = $AWS_REGION
            "@

            # Écrire le contenu dans le fichier config
            $configContent | Set-Content -Path $configFilePath
            Write-Host "Fichier config créé : $configFilePath"

            # Créer le fichier credentials
            $credentialsFilePath = "$folderPath\credentials"
            $credentialsContent = @"
            [default]
            aws_access_key_id = $AWS_ACCESS_KEY_ID
            aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
            "@

            # Écrire le contenu dans le fichier credentials
            $credentialsContent | Set-Content -Path $credentialsFilePath
            Write-Host "Fichier credentials créé : $credentialsFilePath"

          } else {
              Write-Host "Le dossier existe déjà : $folderPath"
          }

        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Démarrer Astro
        run: astro dev start

      - name: se connecter au container airflow
        run: astro dev bash
       
      - name: Lancer le DAG nyc_taxi_trips
        run: airflow dags trigger nyc_taxi_trips